Book/urls.py
from django.urls import path
from . import views

app_name = 'Book'

urlpatterns = [
    path('', views.index, name='index'),
    path('getBooks', views.getBooks, name='getBooks'),
]

Story8/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Book.urls')),
]

Book/models.py
from django.db import models


class Book(models.Model):
    id = models.CharField(max_length=100, primary_key=True)
    cover = models.URLField(max_length=400)
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200, blank=True)
    publishedDate = models.DateField(max_length=100, blank=True)
    publisher = models.CharField(max_length=200, blank=True)

Book/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.core import serializers
import requests

def index(request):
    return render(request, 'Book/book.html')

def getBooks(request):
    response = requests.get('https://www.googleapis.com/books/v1/volumes?q=' + request.GET['keyword'])
    data = response.json()
    return JsonResponse(data)

Book/templates/Book/book.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>📚 Books</title>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800&display=swap" rel="stylesheet"> 
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'book.css' %}">
</head>
<body>
    <center>
        <div class="header container">
            <h1>Search any books <span class="main-color">here.</span></h1><br>
            <div class="container d-flex">
                <input type="text" class="form-control" name="keyword" id="search-box" placeholder="&nbsp;write the title">&nbsp;&nbsp;
                <button class="btn btn-success" id="search-button">Search</button>
            </div>
        </div><br><br><br>
    </center>
        <div class="container">
            <table id="main-table" style="display: none">
            <tr>
                <th>Cover</th>
                <th>Title</th>
                <th>Author</th>
                <th>Publish Date</th>
                <th>Publisher</th>
            </tr>
            </table>
        </div><br><br><br>
    <script>
        const get_books_url = "{% url 'Book:getBooks' %}?keyword=";
    </script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="{% static 'book.js' %}"></script>
</body>
</html>